name: Use API Token

on: 
  push

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print API Token Length
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: echo "API Token length: ${#API_TOKEN}"
